-- CreateEnum
CREATE TYPE "public"."DietType" AS ENUM ('VEGETARIANO', 'VEGANO', 'OMNIVORO', 'JEJUM_INTERMITENTE', 'CETOGENICA', 'BAIXO_CARBOIDRATO', 'ALTO_PROTEINA', 'MEDITERRANEA', 'SEM_GLUTEN', 'SEM_LACTOSE');

-- AlterTable
ALTER TABLE "public"."diets" ADD COLUMN     "type" "public"."DietType" NOT NULL DEFAULT 'OMNIVORO';
